ActivityWatcher.GetServerLocation() Http optimization
pizzaboxer/bloxstrap pull request #1610
Opened 2024-04-13 02:45 UTC by Redusofficial

Changed GetServerLocation() to only make a single request to ipinfo.io to retrieve the needed location information

2024-04-13 04:47 UTC, pizzaboxer commented
@bluepilledgreat Did we already know about this? I could've sworn there was a reason we avoided using this when we first implemented it.

2024-04-13 11:17 UTC, bluepilledgreat commented
> @bluepilledgreat Did we already know about this? I could've sworn there was a reason we avoided using this when we first implemented it.

¯\_(ツ)_/¯

2024-04-14 13:33 UTC, bluepilledgreat requested changes
Please properly test your code to see if it works and even builds

2024-04-14 13:33 UTC, bluepilledgreat commented on Bloxstrap/Integrations/ActivityWatcher.cs
> +                locationInformation = await Http.GetJson<IPInfoResponse>($"https://ipinfo.io/{ActivityMachineAddress}/json");
`locationInformation` is not properly initialised and will cause an error on build.

2024-04-14 13:33 UTC, bluepilledgreat commented on Bloxstrap/Models/IPInfoResponse.cs
> +        public string City { get; set; }
Make all the string properties nullable to avoid build warnings.

2024-04-14 13:41 UTC, bluepilledgreat requested changes

2024-04-14 13:41 UTC, bluepilledgreat commented on Bloxstrap/Models/IPInfoResponse.cs
> +        public string IP { get; set; }
Only include properties in the response class that are used by the original code.

2024-04-14 21:06 UTC, bluepilledgreat commented
Please actually bother to build and test the build or I'm closing the PR.

2024-04-14 21:07 UTC, Redusofficial commented
I'm currently doing that

2024-05-12 20:11 UTC, pizzaboxer commented
Looks good, let me make some more changes.

2024-05-12 20:15 UTC, bluepilledgreat commented
> Looks good, let me make some more changes.

Have you tested it?

2024-05-12 20:20 UTC, pizzaboxer commented
Yeah, it all works.

2024-05-12 20:20 UTC, pizzaboxer approved these changes

2024-05-12 20:25 UTC, bluepilledgreat approved these changes

2024-05-12 20:29 UTC, merged