Added IP2Location.io API as failover geolocation API
pizzaboxer/bloxstrap pull request #2700
Opened 2024-08-21 05:33 UTC by ip2location

2024-08-21 10:24 UTC, Vlad55432 commented
not a dev, but is this better than stock?

2024-08-21 18:49 UTC, axellse requested changes
also two more things: 

1. Has ipinfo ever been down? otherwise this seems kinda unnecessary.
2. This "ip2location" api is a service you own, and searching for "ip location api" on google i couldn't find it, even after scrolling 5 pages. If a fallback service would be added it would make a lot more sense to use a highly ranked and popular one instead.
3.
![bild](https://github.com/user-attachments/assets/34ec31f3-496b-499f-99ab-60bc4db4928e)
Its limited to 500 queries per day, then it costs money?? now it makes even less sense to add this, considering there are many other services doing it for completly free lol.

2024-08-21 18:49 UTC, axellse commented on Bloxstrap/Integrations/ActivityWatcher.cs
> +				if (!ActivityInGame)
what is going on with the indentation here lol

2024-08-21 20:20 UTC, Storm-930 commented
dude if you want to geolocate IPs you got angry IP scanner for that

2024-08-21 20:30 UTC, pizzaboxer commented
i am in awe at the strategy here of e-stalking repos using competing geolocation apis but no thank you

2024-08-21 20:30 UTC, closed without merging

2024-08-21 21:26 UTC, WaviestBalloon commented
> i am in awe at the strategy here of e-stalking repos using competing geolocation apis but no thank you

And the fact they do this for multiple languages is crazy

2024-08-24 05:50 UTC, abdullahdevrel commented
Hey folks,

I work for IPinfo. Thank you for your decision to continue using our service.

We respect the decision of this project's maintainers to choose which IP data provider they use, but please do let us know if there is any way we can do better. We have continuously made investments in supporting OSS projects, such as releasing our free full-accuracy database, community platform, community events etc.

I, too, regularly reach out to open-source projects, but I try to do so respectfully. However, I do not do it as a business strategy, as the data/API I pitch is completely free. We surely have an advantage over some of our competitors, and I am pretty confident in our data and the developer experience we provide. 

Just for context:

- IPinfo.io provides 1,000 requests per day without a token.
- IPinfo provides 50,000 requests per month with a free tier token.
- Universal access to a globally distributed load-balancing network regardless of access tier.
- Higher accuracy driven by latency-based IP geolocation methods. ([Blog post](https://ipinfo.io/blog/probe-network-how-we-make-sure-our-data-is-accurate/))
- Free HTTPS/SSL encryption
- Free IP to Country ASN database (daily updates, full accuracy, zero compromise)
- Bunch of free libraries, integrations, partnerships with platforms, online tools and developer tools
- An entire community platform dedicated to developers
- Great uptime hours and the capacity to support billions of requests each hour.


Just let me know if you have any feedback for us, and I will try my best to help.

Best Regards,
Abdullah (DevRel @ IPinfo.io)