Add studio support
pizzaboxer/bloxstrap pull request #739
Opened 2023-10-04 11:56 UTC by bluepilledgreat

2023-10-04 17:35 UTC, EasternBloxxer approved these changes
LGTM

2023-10-05 06:37 UTC, nakoyasha requested changes

2023-10-05 06:37 UTC, nakoyasha commented on Bloxstrap/UI/ViewModels/Bootstrapper/ByfronDialogViewModel.cs
>          {
I think it'd be better to pass version info (ex. guid, string, etc) as a constructor argument. Far cleaner and avoids having to figure out it out here.

2023-10-05 06:38 UTC, nakoyasha commented
Overall LGTM, but I feel like Studio and Player should be separated into their own "instances", I don't think it's the greatest idea to have both share the same settings, but that's out of the scope  of this PR.

2023-10-05 07:16 UTC, EasternBloxxer commented
> Overall LGTM, but I feel like Studio and Player should be separated into their own "instances", I don't think it's the greatest idea to have both share the same settings, but that's out of the scope  for this PR.

Yeah as there are flags for player that make studio not launch

2023-10-05 09:44 UTC, passionfr7it commented
i support !

2023-10-07 18:31 UTC, apprehensions commented on Bloxstrap/App.xaml.cs
> +                }
You can simply pass Studio `-protocolString`, the same can be said for player by simply providing the launch URI, as player and studio can handle the URI independently!

2023-10-10 21:28 UTC, pizzaboxer commented
Looks good, provids a great base to work with.

2023-10-10 21:31 UTC, merged