Localization zh cn
pizzaboxer/bloxstrap pull request #935
Opened 2023-11-14 04:53 UTC by xiuluoshashen

This PR has added Simplified Chinese translations
I will strive to ensure the accuracy and fluency of the translations. Any feedback on the translations is welcome to improve their quality.

2023-12-05 08:06 UTC, 1011025m commented on Bloxstrap/Resources/Strings.zh-CN.resx
> +    <value>新出现的</value>
這個 ”New“ 在選單出現的意思是 ”添加“

2023-12-05 08:16 UTC, 1011025m requested changes
Change the translations a little bit according to the comments

有幾個需要改善的地方，可以根據留言作出更改

2023-12-05 08:16 UTC, 1011025m commented on Bloxstrap/Resources/Strings.zh-CN.resx
> +    <value>新出现的</value>
這個 ”New“ 在選單中的意思是 ”添加“

2023-12-05 08:16 UTC, 1011025m commented on Bloxstrap/Resources/Strings.zh-CN.resx
> +    <value>Bloxstrap将在桌面放置一个图标,在下次启动Roblox时启动它</value>
原文的意思是：
下一次Bloxstrap啓動時，會在桌面上放置捷徑讓你啓動Roblox

2023-12-05 08:16 UTC, 1011025m commented on Bloxstrap/Resources/Strings.zh-CN.resx
> +    <value>选择Roblox应该使用的渲染器,VR需要Direct3D/Automatic</value>
這個設定中“Automatic”的選項是用 Enums.FlagPresets.RenderingMode.Default 的，把它寫成“自動”就可以

2023-12-05 08:16 UTC, 1011025m commented on Bloxstrap/Resources/Strings.zh-CN.resx
> +    <value>允许在discord加入</value>
把Discord的第一個D換成大寫

2024-03-01 20:15 UTC, pizzaboxer commented
https://github.com/pizzaboxer/bloxstrap/pull/932#issuecomment-1973847768

2024-03-01 20:15 UTC, closed without merging